# Generated by Django 2.2 on 2020-05-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_number',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
