# Generated by Django 2.2.4 on 2019-08-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='refunded',
            field=models.BooleanField(default=False),
        ),
    ]
