# Generated by Django 2.2.4 on 2019-09-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='partial_refunded',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='refunded',
        ),
        migrations.AddField(
            model_name='refund',
            name='partial_refund',
            field=models.BooleanField(default=False),
        ),
    ]
