# Generated by Django 2.2.4 on 2019-09-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_housepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='housepayment',
            name='arqam_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
