# Generated by Django 2.2.4 on 2019-09-06 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20190906_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housepayment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='housepayment',
            name='arqam_fee',
        ),
    ]
