# Generated by Django 2.2.4 on 2019-09-09 16:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_auto_20190903_1147'),
        ('payments', '0007_auto_20190906_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('house', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='houses.House')),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payout',
        ),
        migrations.CreateModel(
            name='HouseBalanceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('house_balance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.HouseBalance')),
                ('house_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.HousePayment')),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.Payout')),
                ('refund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.Refund')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.Transaction')),
            ],
        ),
    ]
