# Generated by Django 2.2.4 on 2019-09-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_auto_20190909_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='housebalancelog',
            name='opening_balance',
            field=models.BooleanField(default=False),
        ),
    ]
