# Generated by Django 2.2.4 on 2019-09-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_transaction_house_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='email',
            field=models.EmailField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
