# Generated by Django 2.2.4 on 2019-09-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_transaction_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
