# Generated by Django 2.2.4 on 2019-09-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_payout_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='freeze',
            field=models.BooleanField(default=True),
        ),
    ]
