# Generated by Django 2.2.4 on 2019-09-10 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_auto_20190903_1147'),
        ('payments', '0013_payout_freeze'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='freeze',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PayoutSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.House')),
            ],
        ),
        migrations.CreateModel(
            name='Etransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=300)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('payout_setting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payments.PayoutSetting')),
            ],
        ),
    ]
