# Generated by Django 2.2.4 on 2019-09-10 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_auto_20190910_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='payout_setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.PayoutSetting'),
        ),
        migrations.AddField(
            model_name='payoutsetting',
            name='name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
