# Generated by Django 2.2.5 on 2019-09-20 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_auto_20190919_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payoutsetting',
            name='etransfer',
        ),
        migrations.DeleteModel(
            name='Etransfer',
        ),
    ]
