# Generated by Django 2.2.6 on 2019-10-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0020_refund_house_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransfer',
            name='account',
            field=models.CharField(max_length=12),
        ),
    ]
