# Generated by Django 2.2.7 on 2019-12-04 17:45

from django.db import migrations, models
import payments.models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0023_auto_20191204_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payoutsetting',
            name='bank_transfer',
        ),
        migrations.AddField(
            model_name='payoutsetting',
            name='account',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payoutsetting',
            name='institution',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payoutsetting',
            name='official_document',
            field=models.FileField(blank=True, null=True, upload_to=payments.models.official_document_location, validators=[payments.models.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='payoutsetting',
            name='transit',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BankTransfer',
        ),
    ]
