# Generated by Django 2.2.7 on 2019-12-05 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0024_auto_20191204_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='code_fail_reason',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='failed',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='failure_code',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='failure_message',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='reason',
        ),
    ]
