# Generated by Django 2.2.7 on 2019-12-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0026_auto_20191211_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housebalance',
            name='gross_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='housebalancelog',
            name='gross_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True),
        ),
    ]
