# Generated by Django 2.2 on 2020-04-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0027_auto_20191211_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='live_video_transaction',
            field=models.BooleanField(default=False),
        ),
    ]
