# Generated by Django 2.2 on 2020-04-13 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0028_transaction_live_video_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='live_video_transaction',
        ),
    ]
