# Generated by Django 2.2 on 2020-04-13 19:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0023_auto_20200303_1610'),
        ('payments', '0029_remove_transaction_live_video_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArqamHouseServiceFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('house', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='houses.House')),
            ],
        ),
        migrations.AddField(
            model_name='housebalancelog',
            name='arqam_house_service_fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.ArqamHouseServiceFee'),
        ),
    ]
