# Generated by Django 2.2 on 2020-04-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0031_arqamhouseservicefee_live_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='arqamhouseservicefee',
            name='free',
            field=models.BooleanField(default=False),
        ),
    ]
