# Generated by Django 2.2 on 2020-04-15 19:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0032_arqamhouseservicefee_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arqamhouseservicefee',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=6, null=True),
        ),
    ]
