# Generated by Django 2.2 on 2020-05-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0034_transaction_donation_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='donation_refund',
            field=models.BooleanField(default=False),
        ),
    ]
