# Generated by Django 2.0.3 on 2018-08-27 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20180428_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(default='Canada', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='timezone',
            field=models.CharField(choices=[('Canada/Atlantic', 'Canada Atlantic (-4:00 UTC)'), ('Canada/Central', 'Canada Central (-6:00 UTC)'), ('Canada/Eastern', 'Canada Eastern (-5:00 UTC)'), ('Canada/East-Saskatchewan', 'Canada East-Saskatchewan (-6:00 UTC)'), ('Canada/Mountain', 'Canada Mountain (-7:00 UTC)'), ('Canada/Newfoundland', 'Canada Newfoundland (-3:30 UTC)'), ('Canada/Pacific', 'Canada Pacific (-8:00 UTC)'), ('Canada/Saskatchewan', 'Canada Saskatchewan (-6:00 UTC)'), ('Canada/Yukon', 'Canada Yukon (-8:00 UTC)')], default='Canada/Eastern', max_length=150),
        ),
    ]
