# Generated by Django 2.0.3 on 2018-04-29 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.CITIES_CITY_MODEL),
        ('cities', '0011_auto_20180108_0706'),
        ('profiles', '0002_auto_20180428_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.CITIES_CITY_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(default='Canada', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.Region'),
        ),
        migrations.AddField(
            model_name='profile',
            name='timezone',
            field=models.CharField(choices=[('Canada/Atlantic', 'Canada Atlantic (-4:00 UTC)'), ('Canada/Central', 'Canada Central (-6:00 UTC)'), ('Canada/Eastern', 'Canada Eastern (-5:00 UTC)'), ('Canada/East-Saskatchewan', 'Canada East-Saskatchewan (-6:00 UTC)'), ('Canada/Mountain', 'Canada Mountain (-7:00 UTC)'), ('Canada/Newfoundland', 'Canada Newfoundland (-3:30 UTC)'), ('Canada/Pacific', 'Canada Pacific (-8:00 UTC)'), ('Canada/Saskatchewan', 'Canada Saskatchewan (-6:00 UTC)'), ('Canada/Yukon', 'Canada Yukon (-8:00 UTC)')], default='Canada/Eastern', max_length=150),
        ),
    ]
