# Generated by Django 2.2 on 2020-02-20 21:43

from django.db import migrations
import profiles.models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=profiles.models.image_location, validators=[profiles.models.validate_file_size]),
        ),
    ]
