# Generated by Django 2.2 on 2020-04-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20200220_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='temp_password',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
