# Generated by Django 2.2 on 2020-11-26 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_address_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='region',
        ),
    ]
