# Generated by Django 2.0 on 2018-01-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, max_length=175),
        ),
        migrations.AddField(
            model_name='event',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
