# Generated by Django 2.2.3 on 2019-07-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190726_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
