# Generated by Django 2.0.3 on 2018-06-03 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180104_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParagraphElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='descriptionitem',
            name='text_block',
        ),
        migrations.AddField(
            model_name='descriptionitem',
            name='order_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='descriptionitem',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='paragraphelement',
            name='description_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.DescriptionItem'),
        ),
    ]
