# Generated by Django 2.2.3 on 2019-07-31 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('events', '0003_eventorder_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventorder',
            name='failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventorder',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='payments.Transaction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventquestion',
            name='order_question',
            field=models.BooleanField(default=False),
        ),
    ]
