# Generated by Django 2.2.4 on 2019-09-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190903_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventorder',
            name='partial_refund',
            field=models.BooleanField(default=False),
        ),
    ]
