# Generated by Django 2.2.4 on 2019-09-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventorder_partial_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
