# Generated by Django 2.2.4 on 2019-08-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20190801_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventorder',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
