# Generated by Django 2.2.4 on 2019-09-03 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20190903_1451'),
        ('events', '0005_attendee_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventOrderRefund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Attendee')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.EventOrder')),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.Refund')),
            ],
        ),
    ]
