# Generated by Django 2.2.4 on 2019-08-10 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventorder_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='slug',
        ),
    ]
