# Generated by Django 2.2.4 on 2019-09-03 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventorderrefund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventorderrefund',
            name='attendee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Attendee'),
        ),
        migrations.AlterField(
            model_name='eventorderrefund',
            name='refund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.Refund'),
        ),
    ]
