# Generated by Django 2.2.4 on 2019-08-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_attendee_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='amount_available',
            field=models.PositiveSmallIntegerField(blank=True, default=1000, null=True),
        ),
    ]
