# Generated by Django 2.2.4 on 2019-08-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20190810_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='amount_available',
            field=models.PositiveSmallIntegerField(blank=True, default=3000, null=True),
        ),
    ]
