# Generated by Django 2.2.4 on 2019-09-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_eventcartitem_cart_item_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='amount_available',
            field=models.PositiveSmallIntegerField(blank=True, default=500, null=True),
        ),
    ]
