# Generated by Django 2.2.4 on 2019-09-17 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20190912_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendeecommonquestions',
            old_name='notes',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='attendeecommonquestions',
            old_name='notes_required',
            new_name='address_required',
        ),
    ]
