# Generated by Django 2.0.3 on 2018-06-13 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20180606_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendeeGeneralQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.BooleanField(default=True)),
                ('first_name_required', models.BooleanField(default=True)),
                ('last_name', models.BooleanField(default=True)),
                ('last_name_required', models.BooleanField(default=True)),
                ('gender', models.BooleanField(default=True)),
                ('gender_required', models.BooleanField(default=True)),
                ('email', models.BooleanField(default=False)),
                ('email_required', models.BooleanField(default=False)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
        migrations.CreateModel(
            name='EventGeneralQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.BooleanField(default=False)),
                ('notes_required', models.BooleanField(default=False)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
    ]
