# Generated by Django 2.2.4 on 2019-09-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20190917_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='note',
        ),
        migrations.AddField(
            model_name='attendee',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
