# Generated by Django 2.2.4 on 2019-08-21 16:43

from django.db import migrations, models
import events.models.attendees


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_eventemailconfirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=None),
        ),
    ]
