# Generated by Django 2.0.3 on 2018-06-18 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_attendeegeneralquestions_eventgeneralquestions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendeegeneralquestions',
            name='gender_required',
        ),
    ]
