# Generated by Django 2.2.4 on 2019-08-21 17:17

from django.db import migrations, models
import events.models.orders


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_attendee_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='pdf',
        ),
        migrations.AddField(
            model_name='eventorder',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=events.models.orders.pdf_location),
        ),
    ]
