# Generated by Django 2.2.4 on 2019-08-21 19:55

from django.db import migrations, models
import events.models.orders


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20190821_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventorder',
            name='qrcode',
            field=models.FileField(blank=True, null=True, upload_to=events.models.orders.qrcode_location),
        ),
    ]
