# Generated by Django 2.0.3 on 2018-08-08 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20180808_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendeegeneralquestions',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='attendeegeneralquestions',
            name='first_name_required',
        ),
        migrations.RemoveField(
            model_name='attendeegeneralquestions',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='attendeegeneralquestions',
            name='last_name_required',
        ),
    ]
