# Generated by Django 2.2.5 on 2019-09-21 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20190921_1418'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkin',
        ),
    ]
