# Generated by Django 2.0.3 on 2018-08-27 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20180808_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendeegeneralquestions',
            name='name',
        ),
        migrations.RemoveField(
            model_name='attendeegeneralquestions',
            name='name_required',
        ),
    ]
