# Generated by Django 2.2.5 on 2019-09-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_delete_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='ticket_buyer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='ticket_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='ticket_pass_fee',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='ticket_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
