# Generated by Django 2.2.4 on 2019-08-21 20:30

from django.db import migrations, models
import events.models.orders


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_remove_eventorder_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventorder',
            name='code',
            field=models.ImageField(blank=True, null=True, upload_to=events.models.orders.qrcode_location),
        ),
    ]
