# Generated by Django 2.2.5 on 2019-09-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20190923_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcartitem',
            name='pay',
            field=models.BooleanField(default=True),
        ),
    ]
