# Generated by Django 2.2.4 on 2019-08-22 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_eventorder_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='sale_end',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='sale_price',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='sale_start',
        ),
    ]
