# Generated by Django 2.1 on 2019-03-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_event_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descriptionitem',
            name='event',
        ),
        migrations.RemoveField(
            model_name='paragraphelement',
            name='description_item',
        ),
        migrations.AlterField(
            model_name='event',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='DescriptionItem',
        ),
        migrations.DeleteModel(
            name='ParagraphElement',
        ),
    ]
