# Generated by Django 2.2.5 on 2019-09-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20190924_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcart',
            name='house_created',
            field=models.BooleanField(default=False),
        ),
    ]
