# Generated by Django 2.2.4 on 2019-08-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20190822_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcart',
            name='total_no_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='eventcartitem',
            name='cart_item_total_no_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
