# Generated by Django 2.2.4 on 2019-08-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20190822_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcart',
            name='arqam_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
