# Generated by Django 2.2.5 on 2019-10-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_eventorder_house_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventorder',
            name='public_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
