# Generated by Django 2.2.4 on 2019-08-22 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_eventcart_arqam_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventcart',
            old_name='arqam_fee',
            new_name='arqam_charge',
        ),
    ]
