# Generated by Django 2.2.4 on 2019-08-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_auto_20190822_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcart',
            name='total_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
