# Generated by Django 2.2.5 on 2019-10-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_eventorder_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcartitem',
            name='donation_buyer_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='eventcartitem',
            name='donation_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
