# Generated by Django 2.2.4 on 2019-08-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_auto_20190822_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventorder',
            name='refunded',
            field=models.BooleanField(default=False),
        ),
    ]
