# Generated by Django 2.2.5 on 2019-10-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_auto_20191003_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='express',
            field=models.BooleanField(default=False),
        ),
    ]
