# Generated by Django 2.2.5 on 2019-10-09 18:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_ticket_express'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDiscounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('percentage_amount', models.PositiveSmallIntegerField(blank=True, default=10, null=True)),
                ('use_fixed_amount', models.BooleanField(default=False)),
                ('total_uses', models.PositiveIntegerField(blank=True, default=100, null=True)),
                ('used', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('start', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('tickets', models.ManyToManyField(blank=True, to='events.Ticket')),
            ],
        ),
    ]
