# Generated by Django 2.2.5 on 2019-10-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_auto_20191009_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdiscount',
            name='percentage_amount',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
