# Generated by Django 2.2.5 on 2019-10-09 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_auto_20191009_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdiscount',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
    ]
