# Generated by Django 2.2.5 on 2019-10-10 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_auto_20191009_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcart',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.EventDiscount'),
        ),
        migrations.AddField(
            model_name='eventcart',
            name='invalid_discount_code',
            field=models.BooleanField(default=False),
        ),
    ]
