# Generated by Django 2.2.5 on 2019-10-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_eventcartitem_discount_code_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcartitem',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='eventcartitem',
            name='discount_fixed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='eventcartitem',
            name='discount_percentage_amount',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
