# Generated by Django 2.2.5 on 2019-10-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_eventcartitem_ticket_buyer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcartitem',
            name='ticket_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
