# Generated by Django 2.2.5 on 2019-10-15 15:52

from django.db import migrations, models
import events.models.events
import events.models.orders


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_eventcartitem_ticket_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=events.models.events.image_location, validators=[events.models.events.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='eventorder',
            name='code',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=events.models.orders.qrcode_location),
        ),
    ]
