# Generated by Django 2.2.6 on 2019-10-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0036_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdiscount',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventdiscount',
            name='total_uses',
            field=models.PositiveIntegerField(blank=True, default=1000, null=True),
        ),
    ]
