# Generated by Django 2.2.6 on 2019-10-24 20:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0037_auto_20191017_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcart',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
