# Generated by Django 2.2.6 on 2019-11-01 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0041_remove_chargeerror_code_fail_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargeerror',
            name='failed',
        ),
    ]
