# Generated by Django 2.2.7 on 2019-12-01 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0042_remove_chargeerror_failed'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='refund_policy',
            field=models.CharField(choices=[('standard', 'Standard'), ('7-days', '7-days'), ('30-days', '30-days'), ('no refunds', 'No Refunds')], default='standard', max_length=150),
        ),
    ]
