# Generated by Django 2.2.7 on 2019-12-02 17:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0013_house_email'),
        ('events', '0043_ticket_refund_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestARefund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed', models.BooleanField(default=False)),
                ('attendee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Attendee')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.House')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.EventOrder')),
            ],
        ),
    ]
