# Generated by Django 2.2.7 on 2019-12-02 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0013_house_email'),
        ('events', '0045_auto_20191202_1227'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventRequestARefund',
            new_name='EventRequestRefund',
        ),
    ]
