# Generated by Django 2.2.7 on 2019-12-02 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0013_house_email'),
        ('events', '0046_auto_20191202_1229'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventRequestRefund',
            new_name='EventRefundRequest',
        ),
    ]
