# Generated by Django 2.2.7 on 2019-12-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0047_auto_20191202_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='ticket_refund_policy',
            field=models.CharField(choices=[('standard', 'Standard'), ('7-days', '7-days'), ('30-days', '30-days'), ('no refunds', 'No Refunds')], default='standard', max_length=150),
        ),
    ]
