# Generated by Django 2.2.7 on 2019-12-03 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0048_attendee_ticket_refund_policy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventrefundrequest',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventrefundrequest',
            name='house',
        ),
    ]
