# Generated by Django 2.2.7 on 2019-12-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0049_auto_20191203_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrefundrequest',
            name='dismissed',
            field=models.BooleanField(default=False),
        ),
    ]
