# Generated by Django 2.2 on 2019-12-19 17:33

from django.db import migrations, models
import events.models.attendees


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0051_attendee_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='code',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=events.models.attendees.qrcode_location),
        ),
    ]
