# Generated by Django 2.2 on 2019-12-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0053_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='exclusive',
            field=models.BooleanField(default=False),
        ),
    ]
