# Generated by Django 2.2 on 2020-01-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0054_checkin_exclusive'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='attendees',
            field=models.ManyToManyField(blank=True, to='events.Attendee'),
        ),
    ]
