# Generated by Django 2.2 on 2020-01-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0056_remove_checkin_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='checkins',
            field=models.ManyToManyField(blank=True, to='events.Checkin'),
        ),
    ]
