# Generated by Django 2.2 on 2020-01-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0057_attendee_checkins'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventorder',
            name='checkins',
            field=models.ManyToManyField(blank=True, to='events.Checkin'),
        ),
    ]
