# Generated by Django 2.2 on 2020-01-07 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0059_auto_20200107_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventorder',
            name='checkins',
        ),
    ]
