# Generated by Django 2.2 on 2020-01-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0060_remove_eventorder_checkins'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
