# Generated by Django 2.2 on 2020-01-28 16:49

from django.db import migrations, models
import events.models.events


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0061_checkin_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ics_file',
            field=models.FileField(blank=True, null=True, upload_to=events.models.events.ics_file_location),
        ),
    ]
