# Generated by Django 2.2 on 2020-03-30 17:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0071_auto_20200328_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLiveComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(blank=True, max_length=280, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('event_live', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.EventLive')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
