# Generated by Django 2.2 on 2020-04-02 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0073_eventlivecomment_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allow_non_ticket_live_viewers',
            field=models.BooleanField(default=False),
        ),
    ]
