# Generated by Django 2.2 on 2020-04-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0074_event_allow_non_ticket_live_viewers'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='secret_live_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
