# Generated by Django 2.2 on 2020-04-05 21:12

from django.db import migrations, models
import django.db.models.deletion
import events.models.resources


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0075_event_secret_live_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=events.models.resources.event_resource_location, validators=[events.models.resources.validate_file_extension, events.models.resources.validate_file_size])),
                ('link', models.CharField(blank=True, max_length=320, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
    ]
