# Generated by Django 2.2 on 2020-04-05 22:08

from django.db import migrations, models
import events.models.resources


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0076_eventresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventresource',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=events.models.resources.event_resource_image_location, validators=[events.models.resources.validate_file_size]),
        ),
    ]
