# Generated by Django 2.2 on 2020-04-05 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0077_eventresource_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventresource',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
    ]
