# Generated by Django 2.2 on 2020-04-07 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0078_auto_20200405_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlive',
            name='archive_id',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
