# Generated by Django 2.2 on 2020-04-07 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0080_eventlivearchive'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlivearchive',
            name='archive_location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
