# Generated by Django 2.2 on 2020-04-07 04:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0081_eventlivearchive_archive_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventlivearchive',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
        migrations.AddField(
            model_name='eventlivearchive',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='eventlivearchive',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
