# Generated by Django 2.2 on 2020-04-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0082_auto_20200407_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allow_non_ticket_archive_viewers',
            field=models.BooleanField(default=False),
        ),
    ]
