# Generated by Django 2.2 on 2020-04-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0083_event_allow_non_ticket_archive_viewers'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='secret_archive_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
