# Generated by Django 2.2 on 2020-04-08 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0084_event_secret_archive_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='allow_non_ticket_archive_viewers',
            field=models.BooleanField(default=True),
        ),
    ]
