# Generated by Django 2.2 on 2020-04-08 02:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0085_auto_20200407_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLiveBroadcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('facebook_url', models.CharField(blank=True, max_length=320, null=True)),
                ('youtube_url', models.CharField(blank=True, max_length=320, null=True)),
                ('event_live', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.EventLive')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
