# Generated by Django 2.2 on 2020-04-08 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0086_eventlivebroadcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlivebroadcast',
            name='stream_key',
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
    ]
