# Generated by Django 2.2 on 2020-04-08 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0087_eventlivebroadcast_stream_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventlive',
            old_name='archive_id',
            new_name='broadcast_id',
        ),
    ]
