# Generated by Django 2.2 on 2020-04-13 15:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0027_auto_20191211_1202'),
        ('events', '0088_auto_20200408_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLiveFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscribed_mins', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('archived_mins', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('event_live', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.EventLive')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.Transaction')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
