# Generated by Django 2.2 on 2020-04-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0090_auto_20200413_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlivefee',
            name='archived_mins',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='eventlivefee',
            name='subscribed_mins',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
