# Generated by Django 2.2 on 2020-04-13 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0091_auto_20200413_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventlivefee',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='eventlivefee',
            name='transaction',
        ),
    ]
