# Generated by Django 2.2 on 2020-04-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0093_eventlivefee_arqam_house_service_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlivefee',
            name='presenters',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
