# Generated by Django 2.2 on 2020-04-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0094_eventlivefee_presenters'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlivefee',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
