# Generated by Django 2.2 on 2020-04-14 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0095_eventlivefee_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventlivefee',
            name='amount',
        ),
    ]
