# Generated by Django 2.2 on 2020-04-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0096_remove_eventlivefee_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlivefee',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
