# Generated by Django 2.2 on 2020-04-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0097_eventlivefee_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlivecomment',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
