# Generated by Django 2.2 on 2020-04-28 21:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0098_eventlivecomment_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlive',
            name='live_audience',
            field=models.ManyToManyField(blank=True, related_name='live_audience', to=settings.AUTH_USER_MODEL),
        ),
    ]
