# Generated by Django 2.2 on 2020-05-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0099_eventlive_live_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlivefee',
            name='broadcasted_mins',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
