# Generated by Django 2.2 on 2020-06-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0101_eventlivearchive_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlivefee',
            name='broadcasting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventlivefee',
            name='recording',
            field=models.BooleanField(default=False),
        ),
    ]
