# Generated by Django 2.2 on 2020-06-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0102_auto_20200603_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventlivefee',
            name='broadcasting',
        ),
        migrations.RemoveField(
            model_name='eventlivefee',
            name='recording',
        ),
        migrations.AddField(
            model_name='eventlive',
            name='broadcasting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventlive',
            name='recording',
            field=models.BooleanField(default=False),
        ),
    ]
