# Generated by Django 2.2 on 2020-06-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0104_eventlivearchive_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlivearchive',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
