# Generated by Django 2.2.3 on 2019-07-16 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.PositiveSmallIntegerField(blank=True, default=1)),
                ('help_text', models.CharField(blank=True, max_length=150, null=True)),
                ('required', models.BooleanField(default=False)),
                ('simple_question', models.BooleanField(default=False)),
                ('paragraph_question', models.BooleanField(default=False)),
                ('multiple_choice_question', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=375)),
                ('deleted', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AllTicketQuestionControl',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questions.Question')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
            bases=('questions.question',),
        ),
        migrations.CreateModel(
            name='EventQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questions.Question')),
                ('value', models.CharField(blank=True, max_length=200, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.EventQuestion')),
            ],
            bases=('questions.question',),
        ),
        migrations.CreateModel(
            name='TicketQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questions.Question')),
                ('all_ticket_question_control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.AllTicketQuestionControl')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Ticket')),
            ],
            bases=('questions.question',),
        ),
        migrations.CreateModel(
            name='TicketQuestionMultipleChoiceOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=375)),
                ('deleted', models.BooleanField(default=False)),
                ('ticket_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.TicketQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='EventQuestionMultipleChoiceOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=375)),
                ('deleted', models.BooleanField(default=False)),
                ('event_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.EventQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='AllTicketQuestionMultipleChoiceOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=375)),
                ('deleted', models.BooleanField(default=False)),
                ('all_ticket_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.AllTicketQuestionControl')),
            ],
        ),
    ]
