# Generated by Django 2.2.3 on 2019-07-26 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.PositiveSmallIntegerField(blank=True, default=1)),
                ('help_text', models.CharField(blank=True, max_length=150, null=True)),
                ('required', models.BooleanField(default=False)),
                ('question_type', models.CharField(choices=[('Simple', 'Simple'), ('Long', 'Long'), ('Multiple Choice', 'Multiple Choice')], default='simple', max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=375)),
                ('deleted', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiceOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question')),
            ],
        ),
    ]
