# Generated by Django 2.2.5 on 2019-09-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoice',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
