# Generated by Django 2.0.3 on 2018-06-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_eventquestion_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventquestion',
            name='paragraph_question',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventquestion',
            name='simple_question',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='help_text',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, default=1),
        ),
    ]
