# Generated by Django 2.0.3 on 2018-06-12 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20180606_0054'),
        ('tickets', '0005_ticket_buyer_price'),
        ('questions', '0003_auto_20180612_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllTicketQuestionControl',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questions.Question')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
            bases=('questions.question',),
        ),
        migrations.CreateModel(
            name='TicketQuestion',
            fields=[
                ('eventquestion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questions.EventQuestion')),
                ('all_ticket_question_control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.AllTicketQuestionControl')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Ticket')),
            ],
            bases=('questions.eventquestion',),
        ),
        migrations.RemoveField(
            model_name='eventquestion',
            name='paragraph_question',
        ),
        migrations.RemoveField(
            model_name='eventquestion',
            name='simple_question',
        ),
        migrations.AddField(
            model_name='question',
            name='paragraph_question',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='simple_question',
            field=models.BooleanField(default=False),
        ),
    ]
