# Generated by Django 2.2 on 2020-03-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20191008_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('Simple', 'Text'), ('Long', 'Paragraph Text'), ('Multiple Choice', 'Multiple Choice')], default='Simple', max_length=50),
        ),
    ]
