# Generated by Django 2.0.3 on 2018-06-12 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20180612_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketquestion',
            name='all_ticket_question_control',
        ),
        migrations.RemoveField(
            model_name='ticketquestion',
            name='eventquestion_ptr',
        ),
        migrations.RemoveField(
            model_name='ticketquestion',
            name='ticket',
        ),
        migrations.DeleteModel(
            name='TicketQuestion',
        ),
    ]
