# Generated by Django 2.0.3 on 2018-06-12 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20180606_0054'),
        ('tickets', '0005_ticket_buyer_price'),
        ('questions', '0005_auto_20180612_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questions.Question')),
                ('all_ticket_question_control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.AllTicketQuestionControl')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Ticket')),
            ],
            bases=('questions.question',),
        ),
    ]
