# Generated by Django 2.0.3 on 2018-07-04 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_question_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventQuestionMultipleChoiceOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=375)),
                ('event_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.EventQuestion')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='multiple_choice_question',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(blank=True, max_length=375),
        ),
    ]
