# Generated by Django 2.0.3 on 2018-07-09 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_allticketquestionmultiplechoiceoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketQuestionMultipleChoiceOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=375)),
                ('deleted', models.BooleanField(default=False)),
                ('ticket_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.TicketQuestion')),
            ],
        ),
    ]
