# Generated by Django 2.0.3 on 2018-06-13 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_eventorder'),
        ('answers', '0001_initial'),
        ('attendees', '0001_initial'),
        ('questions', '0006_ticketquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketanswer',
            name='attendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendees.Attendee'),
        ),
        migrations.AddField(
            model_name='ticketanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.TicketQuestion'),
        ),
        migrations.AddField(
            model_name='eventanswer',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.EventOrder'),
        ),
        migrations.AddField(
            model_name='eventanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.EventQuestion'),
        ),
    ]
