# Generated by Django 2.2.3 on 2019-07-16 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('answers', '0001_initial'),
        ('attendees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketanswer',
            name='attendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendees.Attendee'),
        ),
    ]
