# Generated by Django 2.2.3 on 2019-07-16 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        ('orders', '0001_initial'),
        ('answers', '0003_ticketanswer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventanswer',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.EventOrder'),
        ),
        migrations.AddField(
            model_name='eventanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.EventQuestion'),
        ),
    ]
