# Generated by Django 2.2.4 on 2019-09-03 15:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import houses.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=120, null=True)),
                ('slug', models.SlugField(blank=True)),
                ('entity', models.CharField(blank=True, choices=[('individual', 'Individual'), ('company', 'Company')], default='individual', max_length=150, null=True)),
                ('connect_account_created', models.BooleanField(default=False)),
                ('connected_stripe_account_id', models.CharField(max_length=200, null=True)),
                ('front_side', models.ImageField(blank=True, null=True, upload_to=houses.models.temp_file_upload_location)),
                ('back_side', models.ImageField(blank=True, null=True, upload_to=houses.models.temp_file_upload_location)),
                ('legal_document', models.ImageField(blank=True, null=True, upload_to=houses.models.temp_file_upload_location)),
                ('stripe_legal_document_id', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HouseUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('staff', 'Staff')], default='admin', max_length=150)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.House')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
