# Generated by Django 2.2.5 on 2019-09-24 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_auto_20190916_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='back_side',
        ),
        migrations.RemoveField(
            model_name='house',
            name='connect_account_created',
        ),
        migrations.RemoveField(
            model_name='house',
            name='connected_stripe_account_id',
        ),
        migrations.RemoveField(
            model_name='house',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='house',
            name='front_side',
        ),
        migrations.RemoveField(
            model_name='house',
            name='legal_document',
        ),
        migrations.RemoveField(
            model_name='house',
            name='stripe_legal_document_id',
        ),
    ]
