# Generated by Django 2.2.6 on 2019-10-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_auto_20191028_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='house_type',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Business', 'Business'), ('Nonprofit', 'Nonprofit')], default='individual', max_length=150),
        ),
    ]
