# Generated by Django 2.2.6 on 2019-10-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0006_auto_20191029_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='house_type',
            field=models.CharField(blank=True, choices=[('Individual', 'Individual'), ('Business', 'Business'), ('Nonprofit', 'Nonprofit')], max_length=150, null=True),
        ),
    ]
