# Generated by Django 2.2.6 on 2019-11-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0007_auto_20191029_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='address_entered',
            field=models.BooleanField(default=False),
        ),
    ]
