# Generated by Django 2.2.6 on 2019-11-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0008_house_address_entered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housedirector',
            name='dob_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='housedirector',
            name='dob_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='housedirector',
            name='dob_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
