# Generated by Django 2.2.6 on 2019-11-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0010_auto_20191105_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='verification_pending',
            field=models.BooleanField(default=False),
        ),
    ]
