# Generated by Django 2.2.6 on 2019-11-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0011_house_verification_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='business_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
