# Generated by Django 2.2.7 on 2019-12-01 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0012_house_business_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
