# Generated by Django 2.2 on 2019-12-11 21:47

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0013_house_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
