# Generated by Django 2.2 on 2020-01-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0014_house_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='legal_business_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='tax_id',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
