# Generated by Django 2.2 on 2020-01-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0015_auto_20200109_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='tax_id',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
