# Generated by Django 2.2 on 2020-01-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0016_auto_20200109_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='tax_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
