# Generated by Django 2.2 on 2020-02-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0019_house_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='housedirector',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='houseuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
