# Generated by Django 2.2 on 2020-02-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0020_auto_20200220_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseuser',
            name='order_confirmations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='houseuser',
            name='ticket_sale_updates',
            field=models.BooleanField(default=False),
        ),
    ]
