# Generated by Django 2.2 on 2020-02-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0021_auto_20200226_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='houseuser',
            old_name='ticket_sale_updates',
            new_name='ticket_sales',
        ),
        migrations.AddField(
            model_name='house',
            name='order_confirmations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='ticket_sales',
            field=models.BooleanField(default=False),
        ),
    ]
