# Generated by Django 2.2 on 2020-03-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0022_auto_20200227_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='order_confirmations',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='ticket_sales',
            field=models.BooleanField(default=True),
        ),
    ]
