# Generated by Django 2.2 on 2020-04-15 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0023_auto_20200303_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='free_live_video',
            field=models.BooleanField(default=False),
        ),
    ]
