# Generated by Django 2.2 on 2020-04-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0024_house_free_live_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='issue_tax_deductible_receipts',
            field=models.BooleanField(default=False),
        ),
    ]
