# Generated by Django 2.2 on 2020-04-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0025_house_issue_tax_deductible_receipts'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='allow_donations',
            field=models.BooleanField(default=False),
        ),
    ]
