# Generated by Django 2.2 on 2020-04-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0026_house_allow_donations'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
