# Generated by Django 2.2 on 2020-04-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0027_house_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='charitable_registration_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
