# Generated by Django 2.2 on 2020-05-05 15:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0029_auto_20200505_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='donation_amount_score',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='donation_score',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='event_score',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
