# Generated by Django 2.2 on 2020-05-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0030_auto_20200505_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='campaign_view_score',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
