# Generated by Django 2.2 on 2020-05-05 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0032_auto_20200505_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='event_score',
        ),
    ]
