# Generated by Django 2.2 on 2020-05-05 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0033_remove_house_event_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='campaign_view_score',
        ),
    ]
