# Generated by Django 2.2 on 2020-05-20 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0034_remove_house_campaign_view_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='donation_amount_score',
        ),
        migrations.RemoveField(
            model_name='house',
            name='donation_score',
        ),
    ]
