# Generated by Django 2.2 on 2020-06-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0035_auto_20200520_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
