# Generated by Django 2.2.3 on 2019-07-16 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed', models.BooleanField(default=False)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('stripe_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventCartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True)),
                ('donation_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('free_ticket', models.BooleanField(default=False)),
                ('paid_ticket', models.BooleanField(default=False)),
                ('donation_ticket', models.BooleanField(default=False)),
                ('pass_fee', models.BooleanField(default=False)),
                ('ticket_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cart_item_total', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('event_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.EventCart')),
            ],
        ),
    ]
