# Generated by Django 2.0.3 on 2018-06-11 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcartitem',
            name='event_cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carts.EventCart'),
            preserve_default=False,
        ),
    ]
