# Generated by Django 2.0.3 on 2018-06-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_eventcartitem_event_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcartitem',
            name='cart_item_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='eventcartitem',
            name='donation_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='eventcartitem',
            name='free_ticket',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventcartitem',
            name='paid_ticket',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventcartitem',
            name='pass_fee',
            field=models.BooleanField(default=False),
        ),
    ]
