# Generated by Django 2.0.3 on 2018-06-12 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20180612_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcartitem',
            name='donation_ticket',
            field=models.BooleanField(default=False),
        ),
    ]
