# Generated by Django 2.0.3 on 2018-06-12 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_eventcartitem_donation_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcartitem',
            name='ticket_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
