# Generated by Django 2.0.3 on 2018-06-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_eventcartitem_ticket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcart',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventcart',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
