# Generated by Django 2.0.3 on 2018-08-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_auto_20180612_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcartitem',
            name='quantity',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
