# Generated by Django 2.0.3 on 2018-08-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_auto_20180802_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcart',
            name='stripe_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
