# Generated by Django 2.2 on 2020-11-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0002_recipient_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='email',
            field=models.EmailField(blank=True, max_length=300, null=True),
        ),
    ]
