# Generated by Django 2.2 on 2020-11-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0003_auto_20201116_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='counter',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
