# Generated by Django 2.2 on 2020-11-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0004_recipient_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
