# Generated by Django 2.2 on 2020-11-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0006_remove_recipient_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
