# Generated by Django 2.0.3 on 2018-05-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_selecteduserorganization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='entity',
            field=models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], default='individual', max_length=150),
        ),
    ]
