# Generated by Django 2.0.3 on 2018-05-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='connect_account_created',
            field=models.BooleanField(default=False),
        ),
    ]
