# Generated by Django 2.0.3 on 2018-05-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_organization_connect_account_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='entity',
            field=models.CharField(blank=True, choices=[('individual', 'Individual'), ('company', 'Company')], default='individual', max_length=150, null=True),
        ),
    ]
