# Generated by Django 2.0.3 on 2018-05-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_auto_20180524_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='connected_stripe_account_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
