# Generated by Django 2.0.3 on 2018-05-26 00:07

from django.db import migrations, models
import organizations.models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_organization_connected_stripe_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='back_side',
            field=models.ImageField(blank=True, null=True, upload_to=organizations.models.temp_file_upload_location),
        ),
        migrations.AddField(
            model_name='organization',
            name='front_side',
            field=models.ImageField(blank=True, null=True, upload_to=organizations.models.temp_file_upload_location),
        ),
        migrations.AddField(
            model_name='organization',
            name='legal_document',
            field=models.ImageField(blank=True, null=True, upload_to=organizations.models.temp_file_upload_location),
        ),
    ]
