# Generated by Django 2.0.3 on 2018-05-26 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_auto_20180526_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='stripe_legal_document_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
