# Generated by Django 2.0.3 on 2018-06-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_organization_stripe_legal_document_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='stripe_legal_document_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
