# Generated by Django 2.1 on 2019-03-17 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0008_city_timezone'),
        ('organizations', '0010_auto_20180603_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selecteduserorganization',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='selecteduserorganization',
            name='user',
        ),
        migrations.AddField(
            model_name='organization',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.City'),
        ),
        migrations.AddField(
            model_name='organization',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.Country'),
        ),
        migrations.AddField(
            model_name='organization',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.Region'),
        ),
        migrations.DeleteModel(
            name='SelectedUserOrganization',
        ),
    ]
