# Generated by Django 2.2 on 2020-07-15 21:43

from django.db import migrations, models
import django.db.models.deletion
import postcards.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to=postcards.models.image_location, validators=[postcards.models.validate_file_size])),
                ('image_2', models.ImageField(blank=True, null=True, upload_to=postcards.models.image_location, validators=[postcards.models.validate_file_size])),
                ('image_3', models.ImageField(blank=True, null=True, upload_to=postcards.models.image_location, validators=[postcards.models.validate_file_size])),
                ('image_4', models.ImageField(blank=True, null=True, upload_to=postcards.models.image_location, validators=[postcards.models.validate_file_size])),
                ('image_5', models.ImageField(blank=True, null=True, upload_to=postcards.models.image_location, validators=[postcards.models.validate_file_size])),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('amount_sold', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostCardOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=300)),
                ('message', models.CharField(blank=True, max_length=100, null=True)),
                ('message_to_recipient', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('anonymous', models.BooleanField(default=False)),
                ('recipient_name', models.CharField(blank=True, max_length=30, null=True)),
                ('recipient_email', models.EmailField(blank=True, max_length=300, null=True)),
                ('recipient_address', models.CharField(blank=True, max_length=200, null=True)),
                ('recipient_postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('sent_to_recipient', models.BooleanField(default=False)),
                ('post_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='postcards.PostCard')),
            ],
        ),
    ]
