# Generated by Django 2.2 on 2020-07-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcardorder',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='postcardorder',
            name='payment_method_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
