# Generated by Django 2.2 on 2020-07-27 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcards', '0002_auto_20200716_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcardorder',
            name='message',
        ),
        migrations.RemoveField(
            model_name='postcardorder',
            name='recipient_email',
        ),
        migrations.AlterField(
            model_name='postcardorder',
            name='message_to_recipient',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postcardorder',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='postcardorder',
            name='payment_method_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
