# Generated by Django 2.2 on 2020-08-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcards', '0005_auto_20200813_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcardorder',
            name='administrative_area_level_1',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='postcardorder',
            name='locality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='postcardorder',
            name='route',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='postcardorder',
            name='street_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
