# Generated by Django 2.2 on 2020-08-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcards', '0007_postcardorder_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcardorder',
            name='envelope_printed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postcardorder',
            name='message_printed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postcardorder',
            name='name_printed',
            field=models.BooleanField(default=False),
        ),
    ]
