# Generated by Django 2.2 on 2020-09-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcards', '0008_auto_20200818_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcard',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
