# Generated by Django 2.2 on 2020-09-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcards', '0009_postcard_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcardorder',
            name='front_printed',
            field=models.BooleanField(default=False),
        ),
    ]
