# Generated by Django 2.2 on 2020-09-30 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcards', '0010_postcardorder_front_printed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcardorder',
            name='recipient_street_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='postcardorder',
            name='street_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
