# Generated by Django 2.2 on 2020-10-13 19:46

from django.db import migrations, models
import postcards.models


class Migration(migrations.Migration):

    dependencies = [
        ('postcards', '0011_auto_20200929_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcardorder',
            name='finished_image',
            field=models.ImageField(blank=True, null=True, upload_to=postcards.models.order_image_location, validators=[postcards.models.validate_file_size]),
        ),
    ]
