# Generated by Django 2.2 on 2020-10-21 23:18

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('postcards', '0013_auto_20201017_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('code', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('total_uses', models.PositiveIntegerField(blank=True, default=1000, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
