# Generated by Django 2.2 on 2020-10-22 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcards', '0014_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='used',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
