# Generated by Django 2.2 on 2020-10-22 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postcards', '0015_promocode_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcardorder',
            name='promo_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='postcards.PromoCode'),
        ),
    ]
