# Generated by Django 2.2 on 2020-10-26 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postcards', '0017_auto_20201022_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonProfit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='postcard',
            name='non_profit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='postcards.NonProfit'),
        ),
    ]
