# Generated by Django 2.2 on 2020-10-26 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postcards', '0018_auto_20201026_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcard',
            name='non_profit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='postcards.NonProfit'),
        ),
    ]
