# Generated by Django 2.2 on 2020-10-28 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcards', '0019_auto_20201026_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonprofit',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='postcardorder',
            name='donation_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
