# Generated by Django 2.2 on 2020-10-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcards', '0020_auto_20201027_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonprofit',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nonprofit',
            name='website',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='postcard',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
