# Generated by Django 2.2 on 2020-10-28 18:32

from django.db import migrations, models
import postcards.models


class Migration(migrations.Migration):

    dependencies = [
        ('postcards', '0021_auto_20201028_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonprofit',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=postcards.models.non_profit_logo_location, validators=[postcards.models.validate_file_size]),
        ),
    ]
