# Generated by Django 2.2 on 2020-11-01 00:22

from django.db import migrations
import postcards.models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('postcards', '0022_nonprofit_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcard',
            name='image_1',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=postcards.models.image_location, validators=[postcards.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='postcard',
            name='image_2',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=postcards.models.image_location, validators=[postcards.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='postcard',
            name='image_3',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=postcards.models.image_location, validators=[postcards.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='postcard',
            name='image_4',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=postcards.models.image_location, validators=[postcards.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='postcard',
            name='image_5',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=postcards.models.image_location, validators=[postcards.models.validate_file_size]),
        ),
    ]
