# Generated by Django 2.2 on 2020-04-20 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0025_house_issue_tax_deductible_receipts'),
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='house',
        ),
        migrations.CreateModel(
            name='DonationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('pass_fee', models.BooleanField(default=False)),
                ('issue_receipts', models.BooleanField(default=False)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.House')),
            ],
        ),
        migrations.AddField(
            model_name='donation',
            name='donation_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='donations.DonationType'),
        ),
    ]
