# Generated by Django 2.2 on 2020-04-23 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_donation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='public_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
