# Generated by Django 2.2 on 2020-04-23 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_donation_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='pass_fee',
            field=models.BooleanField(default=False),
        ),
    ]
