# Generated by Django 2.2 on 2020-04-23 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_donation_pass_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationtype',
            name='collect_address',
            field=models.BooleanField(default=False),
        ),
    ]
