# Generated by Django 2.2 on 2020-04-23 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_donationtype_collect_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationtype',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
