# Generated by Django 2.2 on 2020-05-20 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0034_transaction_donation_transaction'),
        ('donations', '0011_auto_20200517_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='refund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.Refund'),
        ),
        migrations.AddField(
            model_name='donation',
            name='refund_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='refunded',
            field=models.BooleanField(default=False),
        ),
    ]
