# Generated by Django 2.2 on 2020-05-25 20:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import donations.models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0035_auto_20200520_0320'),
        ('donations', '0012_auto_20200520_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftDonationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to=donations.models.image_location, validators=[donations.models.validate_file_size])),
                ('image_2', models.ImageField(blank=True, null=True, upload_to=donations.models.image_location, validators=[donations.models.validate_file_size])),
                ('image_3', models.ImageField(blank=True, null=True, upload_to=donations.models.image_location, validators=[donations.models.validate_file_size])),
                ('image_4', models.ImageField(blank=True, null=True, upload_to=donations.models.image_location, validators=[donations.models.validate_file_size])),
                ('image_5', models.ImageField(blank=True, null=True, upload_to=donations.models.image_location, validators=[donations.models.validate_file_size])),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.House')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
