# Generated by Django 2.2 on 2020-05-26 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0014_giftdonationitem_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftdonationitem',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='houses.House'),
        ),
    ]
