# Generated by Django 2.2 on 2020-05-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0015_auto_20200526_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='message_to_recipient',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
