# Generated by Django 2.2 on 2020-05-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0016_donation_message_to_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='gift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='recipient_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='recipient_postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
