# Generated by Django 2.2 on 2020-05-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0018_donation_send_e_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftdonationitem',
            name='amount_sold',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
