# Generated by Django 2.2 on 2020-05-27 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0019_giftdonationitem_amount_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='gift',
        ),
        migrations.AddField(
            model_name='donation',
            name='gift_donation_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donations.GiftDonationItem'),
        ),
    ]
