# Generated by Django 2.2 on 2020-05-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0020_auto_20200527_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='gift_donation_item_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
