# Generated by Django 2.2 on 2020-06-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0025_auto_20200613_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
