# Generated by Django 2.2.4 on 2019-09-03 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DescriptionElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='descriptions.Description')),
            ],
        ),
        migrations.CreateModel(
            name='EventDescription',
            fields=[
                ('description_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='descriptions.Description')),
            ],
            bases=('descriptions.description',),
        ),
        migrations.CreateModel(
            name='H1Title',
            fields=[
                ('descriptionelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='descriptions.DescriptionElement')),
                ('title', models.CharField(max_length=150)),
            ],
            bases=('descriptions.descriptionelement',),
        ),
        migrations.CreateModel(
            name='H2Title',
            fields=[
                ('descriptionelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='descriptions.DescriptionElement')),
                ('title', models.CharField(max_length=150)),
            ],
            bases=('descriptions.descriptionelement',),
        ),
        migrations.CreateModel(
            name='H3Title',
            fields=[
                ('descriptionelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='descriptions.DescriptionElement')),
                ('title', models.CharField(max_length=150)),
            ],
            bases=('descriptions.descriptionelement',),
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('descriptionelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='descriptions.DescriptionElement')),
                ('text', models.TextField()),
            ],
            bases=('descriptions.descriptionelement',),
        ),
    ]
