# Generated by Django 2.0.3 on 2019-02-14 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0016_event_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DescriptionElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventDescription',
            fields=[
                ('description_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='descriptions.Description')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
            bases=('descriptions.description',),
        ),
        migrations.CreateModel(
            name='H1Title',
            fields=[
                ('descriptionelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='descriptions.DescriptionElement')),
                ('title', models.CharField(max_length=150)),
            ],
            bases=('descriptions.descriptionelement',),
        ),
        migrations.AddField(
            model_name='descriptionelement',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='descriptions.Description'),
        ),
    ]
