# Generated by Django 2.2.3 on 2019-07-26 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('descriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdescription',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
    ]
