# Generated by Django 2.0.3 on 2019-02-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptionelement',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
