# Generated by Django 2.0.3 on 2019-02-21 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('descriptions', '0002_descriptionelement_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='H2Title',
            fields=[
                ('descriptionelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='descriptions.DescriptionElement')),
                ('title', models.CharField(max_length=150)),
            ],
            bases=('descriptions.descriptionelement',),
        ),
        migrations.CreateModel(
            name='H3Title',
            fields=[
                ('descriptionelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='descriptions.DescriptionElement')),
                ('title', models.CharField(max_length=150)),
            ],
            bases=('descriptions.descriptionelement',),
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('descriptionelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='descriptions.DescriptionElement')),
                ('title', models.CharField(max_length=150)),
            ],
            bases=('descriptions.descriptionelement',),
        ),
    ]
