# Generated by Django 2.0.3 on 2019-02-21 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descriptions', '0003_h2title_h3title_paragraph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paragraph',
            name='title',
        ),
        migrations.AddField(
            model_name='paragraph',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
