# Generated by Django 2.2 on 2020-01-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_subscriber_engagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='attendance',
            field=models.CharField(blank=True, choices=[('Often', 'often'), ('Sometimes', 'Sometimes'), ('Rarely', 'Rarely')], max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='attendance_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='attendance_subtractor',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='engagement_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='engagement_subtractor',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
