# Generated by Django 2.2 on 2020-01-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0003_auto_20200125_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='attendance_score',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='attendance_subtractor',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='engagement_score',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='engagement_subtractor',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
