# Generated by Django 2.2 on 2020-02-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0005_auto_20200206_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='attendance',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='events_total',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
