# Generated by Django 2.2 on 2020-02-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0006_auto_20200206_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='unsubscribed',
            field=models.BooleanField(default=False),
        ),
    ]
