# Generated by Django 2.2 on 2020-02-06 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0007_subscriber_unsubscribed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('total', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('seen', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('score', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('plain_content', models.TextField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('subscribers_seen', models.ManyToManyField(related_name='subscribers_seen', to='subscribers.Subscriber')),
                ('subscribers_sent_to', models.ManyToManyField(related_name='subscribers_sent_to', to='subscribers.Subscriber')),
            ],
        ),
    ]
