# Generated by Django 2.2 on 2020-02-08 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0019_house_logo'),
        ('subscribers', '0008_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='house',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='houses.House'),
            preserve_default=False,
        ),
    ]
