# Generated by Django 2.2 on 2020-02-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0010_campaign_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='subscribers_seen',
            field=models.ManyToManyField(blank=True, related_name='subscribers_seen', to='subscribers.Subscriber'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='subscribers_sent_to',
            field=models.ManyToManyField(blank=True, related_name='subscribers_sent_to', to='subscribers.Subscriber'),
        ),
    ]
