# Generated by Django 2.2 on 2020-02-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0012_auto_20200211_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
