# Generated by Django 2.2 on 2020-03-03 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0068_eventrefererdomain'),
        ('subscribers', '0013_auto_20200220_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='tickets',
            field=models.ManyToManyField(blank=True, to='events.Ticket'),
        ),
    ]
