# Generated by Django 2.2 on 2020-03-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0068_eventrefererdomain'),
        ('subscribers', '0014_auto_20200303_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='events',
            field=models.ManyToManyField(blank=True, to='events.Event'),
        ),
    ]
