# Generated by Django 2.2 on 2020-03-04 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0015_subscriber_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='tickets',
        ),
    ]
