# Generated by Django 2.2 on 2020-04-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0016_remove_campaign_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='campaigns_total',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='subscriber_score',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
