# Generated by Django 2.2 on 2020-05-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0018_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='audience',
            name='slug',
            field=models.SlugField(blank=True, max_length=175),
        ),
    ]
