# Generated by Django 2.2 on 2020-05-05 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0019_audience_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='attendance_score',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='attendance_total',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='campaigns_total',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='engagement_score',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='engagement_total',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='events_total',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='subscriber_score',
        ),
    ]
