# Generated by Django 2.2 on 2020-05-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0021_auto_20200505_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='total_campaigns_since_subscribed',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='total_events_since_subscribed',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
