# Generated by Django 2.2 on 2020-05-05 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0022_auto_20200505_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='highest_amount_donated',
            new_name='amount_donated',
        ),
    ]
