# Generated by Django 2.2 on 2020-05-05 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0023_auto_20200505_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='donation_amount_score',
        ),
    ]
