# Generated by Django 2.2 on 2020-05-05 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0024_remove_subscriber_donation_amount_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='donation_above_average',
            field=models.BooleanField(default=False),
        ),
    ]
