# Generated by Django 2.2 on 2020-05-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0025_subscriber_donation_above_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
