# Generated by Django 2.2 on 2020-05-07 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0026_campaign_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='event',
        ),
        migrations.AddField(
            model_name='campaign',
            name='audience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscribers.Audience'),
        ),
    ]
