# Generated by Django 2.2 on 2020-05-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0027_auto_20200507_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
