# Generated by Django 2.2 on 2020-05-25 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0028_campaign_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='donation_above_average',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='donation_score',
        ),
    ]
