# Generated by Django 2.0.3 on 2018-06-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='max_amount',
            field=models.PositiveSmallIntegerField(blank=True, default=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='min_amount',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
