# Generated by Django 2.0.3 on 2018-06-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20180611_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='buyer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
