# Generated by Django 2.0.3 on 2018-06-11 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_buyer_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='buyer_price',
        ),
    ]
