# Generated by Django 2.0.3 on 2018-06-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_buyer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='amount_available',
            field=models.PositiveSmallIntegerField(blank=True, default=1000),
        ),
        migrations.AddField(
            model_name='ticket',
            name='amount_sold',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sold_out',
            field=models.BooleanField(default=False),
        ),
    ]
