# Generated by Django 2.0.3 on 2018-07-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticket_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
