# Generated by Django 2.2 on 2020-11-16 19:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import orders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('postcards', '0026_auto_20201108_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=300)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('donation_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fulfilled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('code', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('total_uses', models.PositiveIntegerField(blank=True, default=1000, null=True)),
                ('used', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LineOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('apt_number', models.CharField(blank=True, max_length=20, null=True)),
                ('street_number', models.CharField(blank=True, max_length=20, null=True)),
                ('route', models.CharField(blank=True, max_length=100, null=True)),
                ('locality', models.CharField(blank=True, max_length=100, null=True)),
                ('administrative_area_level_1', models.CharField(blank=True, max_length=4, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('message_to_recipient', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('donation_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('anonymous', models.BooleanField(default=False)),
                ('add_gift_card', models.BooleanField(default=False)),
                ('gift_card', models.CharField(blank=True, choices=[('Apple', 'Apple'), ('Google', 'Google'), ('HomeSense', 'HomeSense'), ('Amazon', 'Amazon'), ('Indigo', 'Indigo'), ('Shoppers', 'Shoppers')], max_length=150, null=True)),
                ('gift_card_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('recipient_name', models.CharField(blank=True, max_length=30, null=True)),
                ('recipient_address', models.CharField(blank=True, max_length=200, null=True)),
                ('recipient_apt_number', models.CharField(blank=True, max_length=20, null=True)),
                ('recipient_street_number', models.CharField(blank=True, max_length=20, null=True)),
                ('recipient_route', models.CharField(blank=True, max_length=100, null=True)),
                ('recipient_locality', models.CharField(blank=True, max_length=100, null=True)),
                ('recipient_administrative_area_level_1', models.CharField(blank=True, max_length=4, null=True)),
                ('recipient_postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('sent_to_recipient', models.BooleanField(default=False)),
                ('payment_intent_id', models.CharField(blank=True, max_length=300, null=True)),
                ('payment_method_id', models.CharField(blank=True, max_length=300, null=True)),
                ('envelope_printed', models.BooleanField(default=False)),
                ('front_printed', models.BooleanField(default=False)),
                ('name_printed', models.BooleanField(default=False)),
                ('message_printed', models.BooleanField(default=False)),
                ('finished_image', models.ImageField(blank=True, null=True, upload_to=orders.models.order_image_location, validators=[orders.models.validate_file_size])),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
                ('post_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='postcards.PostCard')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.PromoCode')),
            ],
        ),
    ]
