# Generated by Django 2.2.3 on 2019-07-16 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_auto_20190716_2009'),
        ('houses', '0001_initial'),
        ('payouts', '0001_initial'),
        ('carts', '0002_auto_20190716_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=150, null=True)),
                ('failed', models.BooleanField(default=False)),
                ('code_fail_reason', models.CharField(blank=True, max_length=250, null=True)),
                ('failure_code', models.CharField(blank=True, max_length=150, null=True)),
                ('failure_message', models.CharField(blank=True, max_length=150, null=True)),
                ('last_four', models.CharField(blank=True, max_length=10, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('network_status', models.CharField(blank=True, max_length=150, null=True)),
                ('reason', models.CharField(blank=True, max_length=150, null=True)),
                ('risk_level', models.CharField(blank=True, max_length=150, null=True)),
                ('seller_message', models.CharField(blank=True, max_length=150, null=True)),
                ('outcome_type', models.CharField(blank=True, max_length=150, null=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('address_line_1', models.CharField(blank=True, max_length=150, null=True)),
                ('address_state', models.CharField(blank=True, max_length=150, null=True)),
                ('address_postal_code', models.CharField(blank=True, max_length=150, null=True)),
                ('address_city', models.CharField(blank=True, max_length=150, null=True)),
                ('address_country', models.CharField(blank=True, max_length=150, null=True)),
                ('house', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='houses.House')),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payouts.Payout')),
            ],
        ),
        migrations.CreateModel(
            name='EventOrder',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Order')),
                ('email', models.EmailField(max_length=300)),
                ('note', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('event_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.EventCart')),
            ],
            bases=('orders.order',),
        ),
    ]
