# Generated by Django 2.0.3 on 2018-06-12 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventorder',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventorder',
            name='event_cart',
        ),
        migrations.DeleteModel(
            name='EventOrder',
        ),
    ]
