# Generated by Django 2.2 on 2020-11-16 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineorder',
            old_name='post_card',
            new_name='postcard',
        ),
    ]
