# Generated by Django 2.2 on 2020-11-16 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0001_initial'),
        ('orders', '0002_auto_20201116_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineorder',
            name='recipient_address',
        ),
        migrations.RemoveField(
            model_name='lineorder',
            name='recipient_administrative_area_level_1',
        ),
        migrations.RemoveField(
            model_name='lineorder',
            name='recipient_apt_number',
        ),
        migrations.RemoveField(
            model_name='lineorder',
            name='recipient_locality',
        ),
        migrations.RemoveField(
            model_name='lineorder',
            name='recipient_name',
        ),
        migrations.RemoveField(
            model_name='lineorder',
            name='recipient_postal_code',
        ),
        migrations.RemoveField(
            model_name='lineorder',
            name='recipient_route',
        ),
        migrations.RemoveField(
            model_name='lineorder',
            name='recipient_street_number',
        ),
        migrations.AddField(
            model_name='lineorder',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipients.Recipient'),
        ),
    ]
