# Generated by Django 2.0.3 on 2018-06-12 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_auto_20180612_0156'),
        ('events', '0009_auto_20180606_0054'),
        ('orders', '0002_auto_20180612_0211'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventOrder',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Order')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('event_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.EventCart')),
            ],
            bases=('orders.order',),
        ),
    ]
