# Generated by Django 2.0.3 on 2018-08-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_eventorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventorder',
            name='email',
            field=models.EmailField(default='zaeem.maqsood@gmail.com', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventorder',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
