# Generated by Django 2.2 on 2020-11-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineorder',
            name='payment_intent_id',
        ),
        migrations.RemoveField(
            model_name='lineorder',
            name='payment_method_id',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
