# Generated by Django 2.2 on 2020-12-02 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_lineorder_sender_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineorder',
            name='address',
        ),
        migrations.RemoveField(
            model_name='lineorder',
            name='administrative_area_level_1',
        ),
        migrations.RemoveField(
            model_name='lineorder',
            name='apt_number',
        ),
        migrations.RemoveField(
            model_name='lineorder',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='lineorder',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='lineorder',
            name='route',
        ),
        migrations.RemoveField(
            model_name='lineorder',
            name='street_number',
        ),
    ]
