# Generated by Django 2.2 on 2020-12-02 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20201201_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='public_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
