# Generated by Django 2.2 on 2020-12-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineorder',
            name='gift_card',
            field=models.CharField(blank=True, choices=[('Tim Hortons', 'Tim Hortons'), ('Starbucks', 'Starbucks'), ('Amazon', 'Amazon')], max_length=150, null=True),
        ),
    ]
