# Generated by Django 2.0.3 on 2018-10-04 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0001_initial'),
        ('orders', '0010_auto_20180806_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventorder',
            name='payout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payouts.EventPayout'),
        ),
    ]
