# Generated by Django 2.0.3 on 2019-02-11 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0002_payout_organization'),
        ('orders', '0011_eventorder_payout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventorder',
            name='payout',
        ),
        migrations.AddField(
            model_name='order',
            name='payout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payouts.Payout'),
        ),
    ]
