# Generated by Django 2.2.3 on 2019-07-16 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('attendees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinattendee',
            name='checkin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Checkin'),
        ),
    ]
