# Generated by Django 2.2.3 on 2019-07-16 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_auto_20190716_2009'),
        ('attendees', '0002_checkinattendee_checkin'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.EventOrder'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Ticket'),
        ),
    ]
