# Generated by Django 2.0.3 on 2018-08-05 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_ticket_deleted'),
        ('attendees', '0002_auto_20180618_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='ticket',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='tickets.Ticket'),
            preserve_default=False,
        ),
    ]
