# Generated by Django 2.0.3 on 2018-08-08 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0003_attendee_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
