# Generated by Django 2.0.3 on 2018-08-08 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0004_attendee_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='last_name',
        ),
    ]
