# Generated by Django 2.0.3 on 2018-08-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0005_auto_20180808_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='slug',
            field=models.SlugField(blank=True, max_length=375),
        ),
    ]
