# Generated by Django 2.0.3 on 2018-11-19 18:32

import attendees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0007_auto_20181031_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='pdf',
            field=models.FileField(blank=True, max_length=600, null=True, upload_to=attendees.models.download_pdf_location),
        ),
    ]
